### ISSUE TITLE
How to use with assert.* interface

### ISSUE THREAD

**Issue by fatso83** [suchipi/chai-jest-snapshot#11]
How would I use this with the `assert` interface? I tried 

```javascript
assert.matchSnapshot(toJson(wrapper));
```
No go.

**Comment by suchipi** [comment]
I don't know. I don't see anything in the chai documentation about how to use helpers with `assert`. I'll have to look into it.

**Comment by fatso83** [comment]
Just as a little tip, after looking into the structure code: I think you can score a quick win by extracting everything except the logic in `index.js` into a small library of its own and release that as a separate package that can be used without Chai.

Before landing on your package, I tried using another stand-alone package, [snap-shot](https://github.com/bahmutov/snap-shot), but it only produced ugly json snapshots, so I switched to this just to get the nice file diffs. Having the possibility of using something like this without the Chai dependency means it could be used with any testing strategy.

My 2 cents :-)

**Comment by suchipi** [comment]
Such a package might just be [`jest-snapshot`](https://github.com/facebook/jest/tree/master/packages/jest-snapshot) itself; its API has gotten more flexible since Jest 14 (I haven't updated to take advantage of that yet, though).

**Comment by suchipi** [comment]
It looks like chai does not automatically extend assert with helpers defined using its API, but you can do this yourself in your test setup file:
```js
const chai = require("chai");
const { expect, assert } = chai;

assert.matchSnapshot = function matchSnapshot(object, ...args) {
  expect(object).to.matchSnapshot(...args);
}
```
