### ISSUE TITLE
Jest Example

### ISSUE THREAD

**Issue by jadengore** [suchipi/chai-jest-snapshot#17]
Does anyone have an example of configuring this package with Jest? I realize I can use the framework-agnostic version for Jest, but I'd prefer if someone has solved automating `__filename` and test name so that I don't have to add that to every test.

**Comment by suchipi** [comment]
You're better off using Jest's built-in snapshot support. If you are overriding jest's global `expect` with chai's, you can use [this approach](https://medium.com/@RubenOostinga/combining-chai-and-jest-matchers-d12d1ffd0303) to make jest's `expect(...).toMatchsnapshot()` work with chai.

**Comment by jadengore** [comment]
@suchipi I ended up separating out Chai matchers as `expect` and Jest matchers as `jestExpect`, seemed to be the easiest solution without monkey patching Jest matchers.

**Comment by suchipi** [comment]
FYI in https://github.com/suchipi/chai-jest-snapshot/pull/23 (which was merged and released in version 1.3.0) it was made possible to do `expect(obj).to.matchSnapshot()` in jest (an example was also added).
