### ISSUE TITLE
Feature Request: Ability to have snapshots be placed in a __snapshots__ folder when using mocha

### ISSUE THREAD

**Issue by madou** [suchipi/chai-jest-snapshot#27]
Hi! 

This would be quite nice if it's possible. This line looks promising: https://github.com/suchipi/chai-jest-snapshot/blob/master/src/buildConfigState.js#L19 but haven't looked into it much.

**Comment by suchipi** [comment]
You should be able to do it like this:
```js
import path from "path";
import chai from "chai";
import chaiJestSnapshot from "chai-jest-snapshot";

chai.use(chaiJestSnapshot);

before(function() {
  chaiJestSnapshot.resetSnapshotRegistry();
});

beforeEach(function() {
  const { currentTest } = this;
  const filename = path.resolve(path.dirname(currentTest.file), "__snapshots__", path.basename(currentTest.file) + ".snap");
  chaiJestSnapshot.setFilename(filename);
  chaiJestSnapshot.setTestName(currentTest.fullTitle());
});
```

Depending on your use-case, you might have to also add code in the `beforeEach` callback to create the `__snapshots__` folder if it doesn't exist.

**Comment by madou** [comment]
works a treat, thanks!

would be good to have this as a config option?

**Comment by suchipi** [comment]
Maybe if enough people request it, but since you can do it using setFilename and setTestName, I don't think it's strictly necessary.

**Comment by nene** [comment]
Would be nice to have this documented in README.

Though, I would expect this package is of interest for people migrating from Jest to Mocha, it would be nice to have a special config option for that.
