### ISSUE TITLE
Jest-like simple interface

### ISSUE THREAD

**Issue by JakeSidSmith** [suchipi/chai-jest-snapshot#6]
Started using `chai-jest-snapshot` recently with `mocha`, but I fear my colleagues will not like the additional effort of supplying a filepath & name for each snapshot.

Do you have any plans to allow a default / automatic filepath / name so that assertions can simply be made with:

```javascript
expect(tree).to.matchSnapshot();
```

I'd love to help out if I can.

P.s. Additionally an easier way to update all snapshots would be nice, but I've not had any thoughts about ways to improve it yet. But if it were possible to do so with `mocha -u` (or similar, as this is already used for `--ui`), that'd be awesome.

**Comment by JakeSidSmith** [comment]
Further thoughts:

You could allow users to define some config for how their snapshots will be output e.g.

```javascript
chai.use(chaiJestSnapshot({
  // To match jest
  path: '__snapshots__', // relative or root
  suffix: '.snap',
  // Additional options
  prefix: 'snapshot'
}));
```

**Comment by truongsinh** [comment]
@JakeSidSmith @suchipi I made it in #7

**Comment by suchipi** [comment]
Thanks @truongsinh. I will try to take a look and offer a proper review sometime either this weekend or next. Also sorry I didn't reply to this earlier @JakeSidSmith, I looked at it from the notification which marked it as read, and then forgot about it

**Comment by JakeSidSmith** [comment]
@suchipi that's kwl, done the same a bunch of times. @truongsinh had quick look at that PR, and looks good. Will take a better look a bit later. :)

**Comment by truongsinh** [comment]
hi @suchipi, how is it going?

**Comment by suchipi** [comment]
Hi, @truongsinh, I haven't forgotten about you, I just had a busy weekend. I'll try to look at this sometime this weekend

**Comment by suchipi** [comment]
This was completed in https://github.com/suchipi/chai-jest-snapshot/pull/7 and I forgot to close this issue
