### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by JakeSidSmith** [suchipi/chai-jest-snapshot#9]
Hey, we started using chai-jest-snapshots with TypeScript this week and ended up having to define our own types for them.

Would you like if I open a PR with the types for you?

Alternatively I could propose them to https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by suchipi** [comment]
I haven't used TypeScript much, so I don't feel I could maintain the typings, so I think DefinitelyTyped would be the appropriate place for them.

**Comment by suchipi** [comment]
Thanks for reaching out, though 😃

**Comment by JakeSidSmith** [comment]
No problem. :)

**Comment by netes** [comment]
@JakeSidSmith Is there any chance you'll publish types for `chai-jest-snapshot`? I can't find them on DefinitelyTyped and I would really appreciate if you'll publish them somewhere :)

**Comment by JakeSidSmith** [comment]
@netes stuck them here for now: https://gist.github.com/JakeSidSmith/fc71903595f84e0c8243266be2325633

**Comment by netes** [comment]
Thanks a lot! :)
